spring.application.name=microservice

spring.datasource.url=jdbc:postgresql://localhost:35432/security
spring.datasource.username=saudagram
spring.datasource.password=saudagram

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


app.jwt.secret=change-me-to-a-secure-random-secret-of-at-least-32-chars
app.jwt.access-ttl-seconds=900
app.jwt.refresh-ttl-seconds=604800

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true